--16
SELECT A.COD_ACT, A.NOMBRE
FROM ACTOR A
WHERE (EXTRACT (YEAR FROM A.FECHA_NAC) < 1950) AND (A.COD_ACT IN (SELECT COD_ACT FROM ACTUA WHERE PAPEL='Principal'))
ORDER BY A.NOMBRE;
--17
SELECT L.COD_LIB, L.TITULO, L.AUTOR
FROM BDA_CINE.LIBRO L
WHERE L.COD_LIB IN (SELECT P.COD_LIB FROM BDA_CINE.PELICULA P WHERE (P.ANYO >= 1990 AND P.ANYO<= 1999))
ORDER BY L.TITULO;
--18
SELECT L.COD_LIB, L.TITULO, L.AUTOR
FROM BDA_CINE.LIBRO L
WHERE L.COD_LIB NOT IN (SELECT P.COD_LIB FROM BDA_CINE.PELICULA P WHERE P.COD_LIB IS NOT NULL);
--19
SELECT G.NOMBRE
FROM GENERO G
WHERE G.COD_GEN IN (SELECT C.COD_GEN FROM CLASIFICACION C WHERE C.COD_PELI NOT IN (SELECT A.COD_PELI FROM ACTUA A))
ORDER BY G.NOMBRE;
--20
SELECT L.TITULO
FROM BDA_CINE.LIBRO L
WHERE L.COD_LIB IN (SELECT P.COD_LIB FROM PELICULA P WHERE P.COD_PELI NOT IN (SELECT COD_PELI FROM ACTUA WHERE COD_ACT NOT IN (SELECT COD_ACT FROM ACTOR WHERE COD_PAIS NOT IN (SELECT COD_PAIS FROM PAIS WHERE NOMBRE = 'USA'))));
--21
SELECT COUNT(*)
FROM PELICULA P
WHERE (P.COD_PELI IN (SELECT COD_PELI FROM CLASIFICACION WHERE COD_GEN IN (SELECT COD_GEN FROM GENERO WHERE NOMBRE='Comedia'))) AND (SELECT COUNT(*) FROM ACTUA WHERE ACTUA.COD_PELI=P.COD_PELI AND ACTUA.PAPEL='Secundario')=1;
--22
SELECT MIN(P.ANYO) AS PRIMER_AÑO
FROM PELICULA P
WHERE EXISTS (SELECT * FROM ACTUA WHERE COD_ACT IN (SELECT COD_ACT FROM ACTOR WHERE NOMBRE='Jude Law') AND ACTUA.PAPEL='Principal' AND ACTUA.COD_PELI=P.COD_PELI);
--23
SELECT COD_ACT, NOMBRE
FROM ACTOR A
WHERE A.FECHA_NAC=(SELECT MIN(FECHA_NAC) FROM ACTOR);

--32
SELECT COD_PAIS, NOMBRE
FROM PAIS
WHERE NOT EXISTS (SELECT * FROM ACTOR WHERE ACTOR.COD_PAIS = PAIS.COD_PAIS AND ((EXTRACT (YEAR FROM ACTOR.FECHA_NAC)<1901 OR (EXTRACT (YEAR FROM ACTOR.FECHA_NAC)>2000))))
ORDER BY NOMBRE;
--33
SELECT COD_ACT, NOMBRE
FROM ACTOR
WHERE NOT EXISTS (SELECT * FROM ACTUA WHERE (ACTOR.COD_ACT=COD_ACT AND PAPEL <> 'Secundario')) AND ACTOR.COD_ACT IN (SELECT COD_ACT FROM ACTUA) --SI NO PONES LO ULTIMO COGE TAMBIEN LOS QUE NO HAN ACTUADO EN NINGUNA PELICULA
ORDER BY NOMBRE;
--34
SELECT NOMBRE
FROM ACTOR
WHERE NOT EXISTS (SELECT * FROM ACTUA WHERE COD_PELI IN (SELECT COD_PELI FROM PELICULA WHERE DIRECTOR='Guy Ritchie') AND ACTOR.COD_ACT NOT IN (SELECT COD_ACT FROM ACTUA WHERE COD_PELI IN (SELECT COD_PELI FROM PELICULA WHERE DIRECTOR='Guy Ritchie'))) AND (SELECT COUNT(*) FROM PELICULA WHERE DIRECTOR = 'Guy Ritchie')>0;
--35
SELECT NOMBRE
FROM ACTOR
WHERE NOT EXISTS (SELECT * FROM ACTUA WHERE COD_PELI IN (SELECT COD_PELI FROM PELICULA WHERE DIRECTOR='John Steel') AND ACTOR.COD_ACT NOT IN (SELECT COD_ACT FROM ACTUA WHERE COD_PELI IN (SELECT COD_PELI FROM PELICULA WHERE DIRECTOR='John Steel'))) AND (SELECT COUNT(*) FROM PELICULA WHERE DIRECTOR = 'John Steel')>0;
--36
SELECT P.COD_PELI, P.TITULO
FROM PELICULA P
WHERE P.DURACION<100 AND 
                            NOT EXISTS(SELECT * FROM ACTOR A1 WHERE EXISTS(SELECT * FROM ACTUA WHERE A1.COD_ACT=ACTUA.COD_ACT AND ACTUA.COD_PELI=P.COD_PELI) AND EXISTS (SELECT * FROM ACTOR A2,ACTUA WHERE A2.COD_ACT=ACTUA.COD_ACT AND ACTUA.COD_PELI=P.COD_PELI AND A1.COD_PAIS<>A2.COD_PAIS)) AND EXISTS (SELECT * FROM ACTUA WHERE ACTUA.COD_PELI=P.COD_PELI);
--37
SELECT P.COD_PELI, P.TITULO, P.ANYO
FROM PELICULA P
WHERE EXISTS(SELECT * FROM ACTUA WHERE ACTUA.COD_PELI=P.COD_PELI) AND NOT EXISTS(SELECT * FROM ACTOR, ACTUA WHERE ACTOR.COD_ACT=ACTUA.COD_ACT AND ACTUA.COD_PELI=P.COD_PELI AND ACTOR.FECHA_NAC>'31/12/1942')
ORDER BY P.TITULO;
--38
SELECT P.COD_PAIS, P.NOMBRE
FROM PAIS P
WHERE NOT EXISTS(SELECT * FROM ACTOR WHERE ACTOR.COD_PAIS=P.COD_PAIS AND ACTOR.COD_ACT NOT IN (SELECT ACTUA.COD_ACT FROM ACTUA, PELICULA WHERE ACTUA.COD_PELI=PELICULA.COD_PELI AND PELICULA.DURACION>120)) AND EXISTS(SELECT * FROM ACTOR,ACTUA WHERE ACTOR.COD_ACT=ACTUA.COD_ACT AND ACTOR.COD_PAIS=P.COD_PAIS)
ORDER BY P.NOMBRE;
--39
SELECT L.COD_LIB, L.TITULO, COUNT(*)
FROM PELICULA P, BDA_CINE.LIBRO L
WHERE P.COD_LIB=L.COD_LIB
GROUP BY L.COD_LIB, L.TITULO
HAVING COUNT(*)>1;
--40
SELECT G.COD_GEN, G.NOMBRE, COUNT(*), AVG(P.DURACION)
FROM GENERO G, CLASIFICACION C, PELICULA P
WHERE G.COD_GEN=C.COD_GEN AND C.COD_PELI=P.COD_PELI
GROUP BY G.COD_GEN, G.NOMBRE
HAVING COUNT(*)>5;
--41
SELECT P.COD_PELI, P.TITULO, COUNT(*)
FROM PELICULA P, CLASIFICACION C, GENERO G
WHERE P.COD_PELI=C.COD_PELI AND C.COD_GEN=G.COD_GEN AND P.ANYO > 2000
GROUP BY P.COD_PELI, P.TITULO;
--42
SELECT P.DIRECTOR
FROM PELICULA P
WHERE P.DIRECTOR LIKE '%George%'
GROUP BY P.DIRECTOR
HAVING COUNT(*)=2;
--43
SELECT P.COD_PELI AS COD, P.TITULO, COUNT(*) AS NUMEROACTORES
FROM PELICULA P, ACTUA A, ACTOR ACT
WHERE P.COD_PELI=A.COD_PELI AND A.COD_ACT=ACT.COD_ACT AND P.COD_PELI IN (SELECT PELICULA.COD_PELI FROM GENERO, CLASIFICACION, PELICULA WHERE GENERO.COD_GEN=CLASIFICACION.COD_GEN AND CLASIFICACION.COD_PELI=PELICULA.COD_PELI GROUP BY PELICULA.COD_PELI, PELICULA.TITULO HAVING COUNT(*)=1)
GROUP BY P.COD_PELI, P.TITULO;
--44
SELECT P.COD_PAIS, P.NOMBRE, COUNT(*)
FROM PAIS P, ACTOR, ACTUA A
WHERE P.COD_PAIS=ACTOR.COD_PAIS AND A.COD_PELI IN (SELECT COD_PELI FROM PELICULA WHERE ANYO >= 1960 AND ANYO < 1970)
GROUP BY P.COD_PAIS, P.NOMBRE;
--45
SELECT G.COD_GEN, G.NOMBRE
FROM GENERO G, CLASIFICACION C, PELICULA P
WHERE G.COD_GEN=C.COD_GEN AND C.COD_PELI=P.COD_PELI
GROUP BY G.COD_GEN, G.NOMBRE
HAVING COUNT(*)=(SELECT MAX(COUNT(*)) FROM GENERO G, CLASIFICACION C, PELICULA P WHERE G.COD_GEN=C.COD_GEN AND C.COD_PELI=P.COD_PELI GROUP BY G.COD_GEN, G.NOMBRE);
--47
SELECT P.COD_PAIS, P.NOMBRE, COUNT(*)
FROM ACTOR, PAIS P
WHERE ACTOR.COD_PAIS=P.COD_PAIS AND ACTOR.COD_ACT IN (SELECT ACTOR.COD_ACT FROM ACTOR, ACTUA A, PELICULA P WHERE ACTOR.COD_ACT=A.COD_ACT AND P.COD_PELI=A.COD_PELI GROUP BY ACTOR.COD_ACT, ACTOR.NOMBRE HAVING COUNT(*)=2)
GROUP BY P.COD_PAIS, P.NOMBRE
HAVING COUNT(*)=(SELECT MAX(COUNT(*)) FROM ACTOR, PAIS P WHERE ACTOR.COD_PAIS=P.COD_PAIS AND ACTOR.COD_ACT IN (SELECT ACTOR.COD_ACT FROM ACTOR, ACTUA A, PELICULA P WHERE ACTOR.COD_ACT=A.COD_ACT AND P.COD_PELI=A.COD_PELI GROUP BY ACTOR.COD_ACT, ACTOR.NOMBRE HAVING COUNT(*)=2) GROUP BY P.COD_PAIS, P.NOMBRE);
--48
SELECT EXTRACT (YEAR FROM FECHA_NAC) AS AÑO, COUNT(*)
FROM ACTOR
GROUP BY EXTRACT (YEAR FROM FECHA_NAC)
HAVING COUNT(*)>3;
--49
SELECT *
FROM PELICULA P
WHERE P.DURACION<100 AND P.COD_PELI IN (SELECT ACTUA.COD_PELI FROM ACTOR,ACTUA WHERE ACTOR.COD_ACT=ACTUA.COD_ACT GROUP BY ACTUA.COD_PELI HAVING COUNT(DISTINCT(ACTOR.COD_PAIS))=1);
--54
SELECT ANYO
FROM BDA_CINE.LIBRO L
WHERE ANYO NOT LIKE '%9%'
UNION
SELECT ANYO
FROM PELICULA
WHERE ANYO NOT LIKE '%9%'
ORDER BY ANYO ASC;
--50
SELECT PAIS.COD_PAIS, PAIS.NOMBRE, COUNT(ACTOR.COD_ACT) AS NUMEROACT
FROM PAIS LEFT JOIN ACTOR ON ACTOR.COD_PAIS=PAIS.COD_PAIS
GROUP BY PAIS.COD_PAIS, PAIS.NOMBRE
ORDER BY NUMEROACT ASC;
--51
SELECT L.COD_LIB, L.TITULO, COUNT(P.COD_PELI) AS NUMEROPELIS
FROM BDA_CINE.LIBRO L LEFT JOIN PELICULA P ON P.COD_LIB=L.COD_LIB
WHERE L.ANYO>1980
GROUP BY L.COD_LIB, L.TITULO;
--55
SELECT G.NOMBRE
FROM GENERO G, CLASIFICACION C, PELICULA P
WHERE P.COD_PELI=C.COD_PELI AND C.COD_GEN=G.COD_GEN AND P.DURACION=(SELECT MAX(P2.DURACION) FROM PELICULA P2);
--56
SELECT A.COD_ACT, A.NOMBRE, A.FECHA_NAC, (SELECT COUNT(*) FROM ACTUA WHERE ACTUA.COD_ACT=A.COD_ACT AND ACTUA.PAPEL='Principal') AS CUANTAS_PRINCIPAL
FROM ACTOR A
WHERE A.FECHA_NAC<'01/01/1948' AND (SELECT COUNT(*) FROM ACTUA WHERE ACTUA.COD_ACT=A.COD_ACT)>1
ORDER BY A.NOMBRE












                                                                            





