// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAB0wVVL_jGmF403Q4iBloI_Iw_Of_OqoY',
    appId: '1:961602192781:android:c56ea8850a94049245e9c4',
    messagingSenderId: '961602192781',
    projectId: 'auth-test-pablo',
    storageBucket: 'auth-test-pablo.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBhijrZDcdaiQhpmTSnHUWTAJBcy3w9ZQM',
    appId: '1:961602192781:ios:ab208a82992335e345e9c4',
    messagingSenderId: '961602192781',
    projectId: 'auth-test-pablo',
    storageBucket: 'auth-test-pablo.appspot.com',
    androidClientId: '961602192781-3rlgd9v5l8l6rkpld9ik13q8c7htmdcc.apps.googleusercontent.com',
    iosClientId: '961602192781-8atp9ivadig11hmbpsvcldk021jb80o1.apps.googleusercontent.com',
    iosBundleId: 'com.example.auth',
  );

}